--1
DROP FUNCTION SCHEDULES;

CREATE FUNCTION SCHEDULES(F_DATE DATE)
RETURNS TABLE(FLIGHT_NUMBER INTEGER,FLIGHT_DATE DATE,DEPT_CITY VARCHAR(20),DEPT_TIME TIME,ARRV_CITY VARCHAR(20),ARRV_TIME TIME )
RETURN 
SELECT S.FLIGHT_NUMBER,FLIGHT_DATA, DEPT_CITY,DEPT_TIME,ARRV_CITY,ARRV_TIME
FROM SCHEDULES S , FLIGHTS F
WHERE F.FLIGHT_DATA = F_DATE AND F.FLIGHT_NUMBER = S.FLIGHT_NUMBER;

SELECT *
FROM TABLE(FN855202.SCHEDULES(DATE('2012-05-23')));

--2
DROP FUNCTION COUNT_CUSTOMERS;

CREATE FUNCTION COUNT_CUSTOMERS(A_CODE CHAR(2), START_FLIGHT_DATA DATE, END_FLIGHT_DATA DATE)
RETURNS TABLE(OCC_ECON_CAP INTEGER,OCC_BUS_CAP INTEGER)
RETURN
SELECT OCC_ECON_CAP,OCC_BUS_CAP
FROM FLIGHTS
WHERE AIRLINE_CODE = A_CODE AND FLIGHT_DATA BETWEEN START_FLIGHT_DATA AND END_FLIGHT_DATA;

SELECT *
FROM TABLE(FN855202.COUNT_CUSTOMERS(CHAR('AA'),DATE('2012-02-02'),DATE('2012-04-04')));

--WHERE AIRLINE_CODE=A_CODE AND START_FLIGHT_DATA=FLIGHT_DATA AND END_FLIGHT_DATA=FLIGHT_DATA;

--3
CREATE VIEW DISPLAY AS 
SELECT NAME, SCHEDULES(CURRENT_DATE), COUNT_CUSTOMERS(getdate() + 1 month - 1 day,getdate())
FROM AIRLINES;

SELECT *
FROM DISPLAY;

create function getdate()
returns date
return select (date('0001-01-01') + (year(current_date - 1 month) - 1) years) 
+ (month (current_date - 1 month) -1 ) months 
from SYSIBM.SYSDUMMY1@;